# This is a basic workflow to help you get started with Actions

name: Deploy Branch Linting & Formatting

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the deploy branch
  push:
    branches: [deploy]
  pull_request:
    branches: [deploy]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: main-pipeline

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Template setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: ">=12.x"

      - name: Install npm
        run: npm install

  js-eslint:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1

      # Exclude the test.js files due to errors about jest functions
      - name: Run ESLint
        run: npx eslint source/assets/scripts/*.js

  js-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Use yarn because installing jest thru npm is costly
      - name: Install modules
        run: yarn

      - name: Run tests
        run: yarn test

  html-validate:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1

      - name: Install HTML validator
        run: npm install --save-dev html-validate

      # Only validates source .html files, can generalize if desired
      - name: Run HTML validator
        run: npx html-validate source/**/*.html

  css-lint:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1

      - name: Install CSS linter
        run: npm install --save-dev stylelint stylelint-config-standard

      # Only validates source .css files, can generalize if desired
      - name: Run CSS linter
        run: npx stylelint source/**/*.css

  js-minify:
    needs: [build, js-eslint, css-lint, html-validate]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1

      - name: Install grunt
        run: npm install grunt

      - name: Install HTML minifier
        run: npm install grunt-contrib-htmlmin --save-dev

      - name: Install CSS minifier
        run: npm install grunt-contrib-cssmin --save-dev

      - name: Install uglifyjs
        run: npm install grunt-contrib-uglify --save-dev

      # Only minifies source files, puts min result into deploy dir
      - name: Run minifier and remove unnecessary files
        run: grunt
